from pathlib import Path
import re

src = Path('v3.4.1.html').read_text(encoding='utf-8')
s = src.replace('MyHockeyHub — V3.4.1', 'MyHockeyHub — V3.4.2', 1)
s = s.replace('V3.4 preview', 'V3.4.2', 1)

css = r'''
/* V3.4.2: explicit Add Players selection flow */
.player-picker-toolbar{display:flex;align-items:center;justify-content:space-between;gap:10px;margin:8px 0 10px}.player-picker-toolbar .count{font-size:.82rem;color:var(--muted)}.player-picker-actions{display:flex;gap:8px;align-items:center}.text-action{border:0;background:none;color:var(--blue);padding:4px 2px;font-weight:780}.pickrow.selectable{grid-template-columns:auto auto minmax(0,1fr) auto;transition:border-color .15s ease,background .15s ease}.pickrow.selectable.selected{border-color:#2d99f3;background:rgba(21,123,220,.12)}.pickbox{width:20px;height:20px;accent-color:#1683eb}.following-pill{display:inline-flex;align-items:center;justify-content:center;border:1px solid rgba(56,232,137,.42);background:rgba(20,106,68,.16);color:var(--green);border-radius:999px;padding:5px 8px;font-size:.68rem;font-weight:850;white-space:nowrap}.picker-submit{position:sticky;bottom:max(8px,env(safe-area-inset-bottom));margin-top:12px;padding-top:8px;background:linear-gradient(180deg,transparent,#09131f 32%)}.picker-submit button{width:100%;min-height:48px;font-weight:850}.picker-help{font-size:.78rem;color:var(--muted);margin:2px 0 8px}
html[data-theme="light"] .picker-submit{background:linear-gradient(180deg,transparent,#fff 32%)}html[data-theme="light"] .pickrow.selectable.selected{background:#edf6ff}
@media(max-width:560px){.pickrow.selectable{grid-template-columns:auto auto minmax(0,1fr) auto}.player-picker-toolbar{align-items:flex-start}.player-picker-actions{gap:10px}.following-pill{font-size:.62rem;padding:4px 7px}}
'''
s = s.replace('</style>', css + '\n</style>', 1)

s = s.replace("state.playerMode='favorites';state.playerRosterTeamId='';state.playerRegistry={};", "state.playerMode='favorites';state.playerRosterTeamId='';state.playerPickerSelection=new Set();state.playerRegistry={};", 1)

old_open = """async function openPlayerPicker(){openDrawer('Add Players','Choose players to follow','<div class=\"muted\">Loading…</div>');const t=myTeam(),myDiv=t?[...t.divisions][0]:'',teams=playerTeamOptions(myDiv),myGroup=teams.find(x=>x.ids.includes(String(t?.id||'')));els.drawerBody.innerHTML=`<div class=\"pickergrid\"><div><label class=\"label\">Division</label><select id=\"playerDivision\">${sortedDivisions().map(d=>`<option value=\"${d.id}\" ${String(d.id)===String(myDiv)?'selected':''}>${esc(d.title)}</option>`).join('')}</select></div><div><label class=\"label\">Team</label><select id=\"playerTeam\"><option value=\"\">All teams</option>${teams.map(x=>`<option value=\"${escAttr(x.ids.join(','))}\" ${myGroup===x?'selected':''}>${esc(x.title)}</option>`).join('')}</select></div><div style=\"grid-column:1/-1\"><label class=\"label\">Search</label><input id=\"playerSearch\" type=\"search\" placeholder=\"Player name or jersey\"></div></div><div id=\"playerPickerStatus\" class=\"muted\" style=\"margin:8px 0\"></div><div id=\"playerPickerList\" class=\"pickerlist\"></div>`;const rebuildTeams=()=>{const d=$('#playerDivision').value,opts=playerTeamOptions(d);$('#playerTeam').innerHTML='<option value=\"\">All teams</option>'+opts.map(x=>`<option value=\"${escAttr(x.ids.join(','))}\">${esc(x.title)}</option>`).join('');loadPlayerPicker()};$('#playerDivision').onchange=rebuildTeams;$('#playerTeam').onchange=loadPlayerPicker;$('#playerSearch').oninput=renderPlayerPicker;await loadPlayerPicker()}"""
new_open = """async function openPlayerPicker(){state.playerPickerSelection=new Set();openDrawer('Add Players','Choose players to follow','<div class=\"muted\">Loading…</div>');const t=myTeam(),myDiv=t?[...t.divisions][0]:'',teams=playerTeamOptions(myDiv),myGroup=teams.find(x=>x.ids.includes(String(t?.id||'')));els.drawerBody.innerHTML=`<div class=\"pickergrid\"><div><label class=\"label\">Division</label><select id=\"playerDivision\">${sortedDivisions().map(d=>`<option value=\"${d.id}\" ${String(d.id)===String(myDiv)?'selected':''}>${esc(d.title)}</option>`).join('')}</select></div><div><label class=\"label\">Team</label><select id=\"playerTeam\"><option value=\"\">All teams</option>${teams.map(x=>`<option value=\"${escAttr(x.ids.join(','))}\" ${myGroup===x?'selected':''}>${esc(x.title)}</option>`).join('')}</select></div><div style=\"grid-column:1/-1\"><label class=\"label\">Search</label><input id=\"playerSearch\" type=\"search\" placeholder=\"Player name or jersey\"></div></div><div id=\"playerPickerStatus\" class=\"muted\" style=\"margin:8px 0 2px\"></div><div class=\"picker-help\">Select players below, then add them to My Players.</div><div class=\"player-picker-toolbar\"><div id=\"playerSelectedCount\" class=\"count\">0 players selected</div><div class=\"player-picker-actions\"><button id=\"playerSelectAll\" class=\"text-action\">Select all</button><button id=\"playerClearSelection\" class=\"text-action\">Clear</button></div></div><div id=\"playerPickerList\" class=\"pickerlist\"></div><div class=\"picker-submit\"><button id=\"addSelectedPlayers\" class=\"primary\" disabled>Add Players</button></div>`;const rebuildTeams=()=>{state.playerPickerSelection.clear();const d=$('#playerDivision').value,opts=playerTeamOptions(d);$('#playerTeam').innerHTML='<option value=\"\">All teams</option>'+opts.map(x=>`<option value=\"${escAttr(x.ids.join(','))}\">${esc(x.title)}</option>`).join('');loadPlayerPicker()};$('#playerDivision').onchange=rebuildTeams;$('#playerTeam').onchange=()=>{state.playerPickerSelection.clear();loadPlayerPicker()};$('#playerSearch').oninput=renderPlayerPicker;$('#playerSelectAll').onclick=()=>{for(const p of currentPlayerPickerList())if(!favPlayerMap()[p.id])state.playerPickerSelection.add(String(p.id));renderPlayerPicker()};$('#playerClearSelection').onclick=()=>{state.playerPickerSelection.clear();renderPlayerPicker()};$('#addSelectedPlayers').onclick=()=>{const d=$('#playerDivision')?.value,teamIds=String($('#playerTeam')?.value||'').split(',').filter(Boolean),key=`${state.seasonId}:${d}:${teamIds.join(',')||'all'}`,all=state.playerCache[key]||[],m=favPlayerMap();for(const id of state.playerPickerSelection){const p=all.find(x=>String(x.id)===String(id))||state.playerRegistry[String(id)];if(p){registerPlayer(p);m[String(id)]=p}}saveFavPlayerMap(m);state.playerPickerSelection.clear();renderPlayerPicker()};await loadPlayerPicker()}"""
if old_open not in s:
    raise SystemExit('openPlayerPicker source not found')
s = s.replace(old_open, new_open, 1)

old_render = re.compile(r"function renderPlayerPicker\(\)\{.*?\}\n\nfunction playerDetailSummary", re.S)
new_render = r'''function currentPlayerPickerList(){const d=$('#playerDivision')?.value,teamIds=String($('#playerTeam')?.value||'').split(',').filter(Boolean),key=`${state.seasonId}:${d}:${teamIds.join(',')||'all'}`,q=String($('#playerSearch')?.value||'').toLowerCase();return(state.playerCache[key]||[]).filter(p=>!q||`${p.name} ${p.teamTitle} ${p.number}`.toLowerCase().includes(q))}
function renderPlayerPicker(){const list=currentPlayerPickerList(),favs=favPlayerMap();list.forEach(registerPlayer);const root=$('#playerPickerList');if(!root)return;root.innerHTML=list.map(p=>{const followed=!!favs[p.id],selected=state.playerPickerSelection.has(String(p.id));return`<div class="pickrow selectable ${selected?'selected':''}"><input class="pickbox" type="checkbox" data-select-player="${escAttr(p.id)}" ${selected?'checked':''} ${followed?'disabled':''} aria-label="Select ${escAttr(p.name)}"><div>${logo({title:p.teamTitle,logo:p.teamLogo,abbr:p.teamAbbr},'xs')}</div><div><button class="player-link pn" data-player="${escAttr(p.id)}">${esc(p.name)} ${p.number?`#${esc(p.number)}`:''}</button><div class="pm">${esc(p.teamTitle||'')} · ${esc(p.position||pretty(p.kind))}</div></div>${followed?'<span class="following-pill">✓ Following</span>':'<span class="muted" style="font-size:.72rem">Select</span>'}</div>`}).join('')||'<div class="empty">No matching players were returned. Try another team or division.</div>';root.querySelectorAll('[data-select-player]').forEach(cb=>cb.onchange=()=>{const id=String(cb.dataset.selectPlayer);cb.checked?state.playerPickerSelection.add(id):state.playerPickerSelection.delete(id);renderPlayerPicker()});const n=state.playerPickerSelection.size,count=$('#playerSelectedCount'),submit=$('#addSelectedPlayers');if(count)count.textContent=`${n} ${n===1?'player':'players'} selected`;if(submit){submit.disabled=n===0;submit.textContent=n?`Add ${n} ${n===1?'Player':'Players'}`:'Add Players'}}

function playerDetailSummary'''
s, n = old_render.subn(new_render, s, count=1)
if n != 1:
    raise SystemExit(f'renderPlayerPicker replacement count={n}')

Path('v3.4.2.html').write_text(s, encoding='utf-8')

stable = Path('gamesheets_plus.html').read_text(encoding='utf-8')
stable = stable.replace('V3.4.1','V3.4.2').replace("'3.4.1'","'3.4.2'").replace("'v3.4.1.html'","'v3.4.2.html'")
start = stable.index('  <div class="items">')
end = stable.index('  <div id="originalNote"', start)
items = '''  <div class="items">\n    <div class="item"><div class="check">✓</div><div><b>Clearer player selection</b><span>Add Players now uses explicit checkboxes, a live selection count, Select all / Clear actions, and a final Add Players button.</span></div></div>\n  </div>\n'''
stable = stable[:start] + items + stable[end:]
Path('gamesheets_plus.html').write_text(stable, encoding='utf-8')

index = Path('index.html').read_text(encoding='utf-8')
index = index.replace('<div class="version"><div class="tag current">V3.4.1</div>', '<div class="version"><div class="tag">V3.4.1</div>', 1)
marker = '<section class="versions">\n'
card = '<div class="version"><div class="tag current">V3.4.2</div><div class="desc"><b>Clearer Add Players selection</b><span>Replaced the ambiguous star-only picker with explicit multi-select checkboxes, selection counts, Select all/Clear controls, and an Add Players confirmation action.</span></div><a class="open" href="v3.4.2.html">Open V3.4.2</a></div>\n'
if marker not in index:
    raise SystemExit('index versions marker not found')
index = index.replace(marker, marker + card, 1)
Path('index.html').write_text(index, encoding='utf-8')
