from pathlib import Path
import json
import re

ROOT = Path('.')
rows = json.loads((ROOT / 'data/seasons.json').read_text(encoding='utf-8'))
assert isinstance(rows, list) and len(rows) >= 900, f'Unexpected season catalog size: {len(rows) if isinstance(rows, list) else "not a list"}'
assert any(int(x.get('SeasonID', -1)) == 15111 and x.get('LeagueName') == 'Delaware Valley Hockey League' for x in rows)

src = (ROOT / 'v3.4.2.html').read_text(encoding='utf-8')
s = src.replace('MyHockeyHub — V3.4.2', 'MyHockeyHub — V3.5', 1)
s = re.sub(r'(<span class="version">)V[^<]+(</span>)', r'\1V3.5\2', s, count=1)
s = s.replace('＋ Add season', '🔎 Find league / season')

css = r'''
/* V3.5: searchable season catalog */
.season-finder{display:grid;gap:12px}.season-search-row{display:grid;grid-template-columns:minmax(0,1fr) 145px;gap:8px}.season-results{display:grid;gap:7px;max-height:55vh;overflow:auto;padding-right:2px}.season-result{width:100%;border:1px solid var(--line);border-radius:13px;background:#102033;color:var(--text);padding:11px;text-align:left;display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px;align-items:center}.season-result:hover,.season-result:focus{border-color:var(--blue);outline:none;background:#122943}.season-result-name{font-weight:860;line-height:1.25}.season-result-sub{color:var(--muted);font-size:.77rem;line-height:1.35;margin-top:3px}.season-result-meta{display:flex;gap:5px;flex-wrap:wrap;margin-top:7px}.season-result-meta .pill{font-size:.64rem}.season-result-side{align-self:start;display:grid;justify-items:end;gap:5px}.season-result-action{color:var(--blue);font-weight:800;white-space:nowrap;font-size:.76rem}.season-match{display:inline-flex;align-items:center;border:1px solid rgba(85,167,255,.38);background:rgba(85,167,255,.08);color:#9dceff;border-radius:999px;padding:3px 7px;font-size:.61rem;font-weight:800}.season-current{border-color:rgba(56,232,137,.38)!important;color:var(--green)!important;background:rgba(56,232,137,.08)!important}.season-finder-status{color:var(--muted);font-size:.78rem;line-height:1.4}.manual-season{border-top:1px solid var(--line);padding-top:12px;margin-top:3px}.manual-season-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px}.catalog-note{font-size:.72rem;color:var(--muted);line-height:1.45}.season-no-results{padding:18px 10px;text-align:center;color:var(--muted);border:1px dashed var(--line);border-radius:12px}.season-result.junk{opacity:.72}
html[data-theme="light"] .season-result{background:#fff;color:var(--text)}html[data-theme="light"] .season-result:hover,html[data-theme="light"] .season-result:focus{background:#f5f9fd}
@media(max-width:560px){.season-search-row{grid-template-columns:1fr}.season-result{grid-template-columns:minmax(0,1fr)}.season-result-side{justify-items:start}.season-result-action{justify-self:start}.manual-season-row{grid-template-columns:1fr}.manual-season-row button{width:100%}}
'''
s = s.replace('</style>', css + '\n</style>', 1)

start = s.index('async function addSeason(){')
end = s.index('async function loadSeason(){', start)
finder_js = r'''let seasonCatalogCache=null,seasonCatalogPromise=null;
const SEASON_ACRONYM_STOP=new Set(['the','of','and','for','at','in','on','a','an','to','by','with','de','la','le','du','des']);
const SEASON_JUNK=/\b(test|testing|copy|sandbox|template|merge|mess\s+around|archived\s+seasons?|demo)\b/i;
function canonicalSeasonRow(r){return{SeasonID:Number(r?.SeasonID??r?.id??0),Sport:String(r?.Sport??r?.sport??'').toLowerCase(),LeagueName:String(r?.LeagueName??r?.leagueName??r?.SeasonName??r?.title??'').trim(),SeasonName:String(r?.SeasonName??r?.title??r?.LeagueName??'').trim(),StartDate:r?.StartDate??r?.start??null,EndDate:r?.EndDate??r?.end??null,StatsUrl:r?.StatsUrl||`https://gamesheetstats.com/seasons/${r?.SeasonID??r?.id??''}`}}
async function loadSeasonCatalog(){if(seasonCatalogCache)return seasonCatalogCache;if(!seasonCatalogPromise)seasonCatalogPromise=fetch('data/seasons.json',{cache:'no-store',credentials:'same-origin'}).then(r=>{if(!r.ok)throw new Error(`Catalog HTTP ${r.status}`);return r.json()}).then(rows=>{if(!Array.isArray(rows))throw new Error('Season catalog is not an array');seasonCatalogCache=rows.map(canonicalSeasonRow).filter(x=>x.SeasonID&&x.SeasonName);return seasonCatalogCache}).catch(e=>{seasonCatalogPromise=null;throw e});return seasonCatalogPromise}
function explicitSeasonAcronyms(row){const text=`${row?.LeagueName||''} ${row?.SeasonName||''}`,out=new Set(),add=v=>{const a=String(v||'').replace(/[^A-Z0-9]/g,'');if(a.length>=2&&a.length<=10&&!/^(?:A|AA|AAA|B|BB|C|MD|U\d+)$/.test(a))out.add(a)};for(const m of text.matchAll(/\(([A-Z][A-Z0-9.\-]{1,10})\)/g))add(m[1]);for(const m of text.matchAll(/(?:^|[\s–—-])([A-Z][A-Z0-9]{1,9})(?=$|[\s–—-])/g))add(m[1]);return[...out]}
function inferredSeasonAcronym(row){let name=String(row?.LeagueName||row?.SeasonName||'').replace(/[’']s\b/gi,'').replace(/\b(?:19|20)\d{2}(?:\s*[-/]\s*(?:19|20)?\d{2})?\b/g,' '),words=(name.match(/[A-Za-z]+/g)||[]).map(x=>x.toLowerCase()).filter(x=>x.length>1&&!SEASON_ACRONYM_STOP.has(x));if(words.length<3||words.length>8)return'';const a=words.map(x=>x[0]).join('').toUpperCase();return a.length>=3&&a.length<=8?a:''}
function seasonIsCurrent(row){const now=new Date(),a=row?.StartDate?new Date(`${row.StartDate}T00:00:00`):null,b=row?.EndDate?new Date(`${row.EndDate}T23:59:59`):null;return!!(a&&b&&!Number.isNaN(+a)&&!Number.isNaN(+b)&&now>=a&&now<=b)}
function seasonRecencyBonus(row){const now=Date.now(),a=row?.StartDate?new Date(`${row.StartDate}T00:00:00`).getTime():NaN,b=row?.EndDate?new Date(`${row.EndDate}T23:59:59`).getTime():NaN,day=86400000;if(Number.isFinite(a)&&Number.isFinite(b)&&now>=a&&now<=b)return 55;if(Number.isFinite(a)&&a>now&&a-now<=180*day)return 28;if(Number.isFinite(b)&&b<now&&now-b<=365*day)return 12;return 0}
function tokenPrefixMatch(field,tokens){const words=String(field||'').split(' ').filter(Boolean);return tokens.every(t=>words.some(w=>w.startsWith(t)))}
function seasonSearchScore(row,rawQuery){const raw=String(rawQuery||'').trim(),q=normalize(raw);if(!q)return null;const compact=q.replace(/\s+/g,''),id=String(row.SeasonID),league=normalize(row.LeagueName),season=normalize(row.SeasonName),tokens=q.split(' ').filter(Boolean);let score=-1,matchType='';const take=(v,t)=>{if(v>score){score=v;matchType=t}};if(id===compact)take(1500,'id');if(league===q)take(1250,'exact-name');if(season===q)take(1220,'exact-season');if(league.startsWith(q))take(1020,'name-prefix');if(season.startsWith(q))take(990,'season-prefix');if(league.includes(q))take(830,'name-contains');if(season.includes(q))take(800,'season-contains');if(tokens.length>1&&tokenPrefixMatch(`${league} ${season}`,tokens))take(730,'token-prefix');const explicit=explicitSeasonAcronyms(row).map(x=>x.toLowerCase());if(explicit.includes(compact))take(1100,'explicit-acronym');else if(compact.length>=2&&explicit.some(x=>x.startsWith(compact)))take(760,'explicit-acronym-prefix');const inferred=inferredSeasonAcronym(row);if(compact.length>=3&&inferred&&inferred.toLowerCase()===compact)take(560,'inferred-acronym');if(score<0)return null;score+=seasonRecencyBonus(row);if(SEASON_JUNK.test(`${row.LeagueName} ${row.SeasonName}`)&&!SEASON_JUNK.test(raw))score-=100;return{score,matchType,inferred}}
function searchSeasonCatalog(rows,query,sport='hockey'){const q=String(query||'').trim();if(q.length<2&&!/^\d{3,}$/.test(q))return[];return(rows||[]).filter(r=>sport==='all'||String(r.Sport).toLowerCase()===sport).map(row=>({row,meta:seasonSearchScore(row,q)})).filter(x=>x.meta).sort((a,b)=>b.meta.score-a.meta.score||(Date.parse(b.row.StartDate||'')||0)-(Date.parse(a.row.StartDate||'')||0)||a.row.LeagueName.localeCompare(b.row.LeagueName,undefined,{numeric:true})).slice(0,30)}
function seasonDate(v){if(!v)return'';const d=new Date(`${v}T12:00:00`);return Number.isNaN(+d)?String(v):new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric',year:'numeric'}).format(d)}
function seasonResultHtml(result){const{row,meta}=result,league=row.LeagueName||row.SeasonName||`Season ${row.SeasonID}`,different=normalize(row.SeasonName)!==normalize(league),dates=[seasonDate(row.StartDate),seasonDate(row.EndDate)].filter(Boolean).join(' – '),current=seasonIsCurrent(row),match=meta.matchType==='inferred-acronym'?`<span class="season-match">Possible acronym · ${esc(meta.inferred)}</span>`:meta.matchType.startsWith('explicit-acronym')?'<span class="season-match">Acronym match</span>':'';return`<button type="button" class="season-result${SEASON_JUNK.test(`${row.LeagueName} ${row.SeasonName}`)?' junk':''}" data-season-result="${escAttr(row.SeasonID)}"><div><div class="season-result-name">${esc(league)}</div>${different?`<div class="season-result-sub">${esc(row.SeasonName)}</div>`:''}<div class="season-result-meta"><span class="pill">${esc(pretty(row.Sport||'hockey'))}</span>${current?'<span class="pill season-current">Current</span>':''}${dates?`<span class="pill">${esc(dates)}</span>`:''}<span class="pill">ID ${esc(row.SeasonID)}</span></div>${match?`<div style="margin-top:6px">${match}</div>`:''}</div><div class="season-result-side"><span class="season-result-action">Use this season ›</span></div></button>`}
function renderSeasonFinderResults(){const input=$('#seasonCatalogSearch'),sport=$('#seasonSportFilter'),root=$('#seasonFinderResults'),status=$('#seasonFinderStatus');if(!input||!root)return;const q=input.value.trim(),hits=searchSeasonCatalog(seasonCatalogCache||[],q,sport?.value||'hockey');if(q.length<2&&!/^\d{3,}$/.test(q)){root.innerHTML='';status.textContent=(seasonCatalogCache?.length||0)?`Search ${(seasonCatalogCache||[]).length.toLocaleString()} known seasons. Start typing a league name, acronym, or season ID.`:'No catalog entries loaded.';return}status.textContent=hits.length?`${hits.length}${hits.length===30?'+':''} match${hits.length===1?'':'es'} · name and word matches rank ahead of inferred acronyms`:'No catalog matches. Try fewer words, a familiar acronym, or use the season ID/URL below.';root.innerHTML=hits.length?hits.map(seasonResultHtml).join(''):'<div class="season-no-results">No matching seasons found in the saved catalog.</div>';root.querySelectorAll('[data-season-result]').forEach(b=>b.onclick=()=>useCatalogSeason(b.dataset.seasonResult))}
async function useCatalogSeason(id){const rows=await loadSeasonCatalog(),r=rows.find(x=>String(x.SeasonID)===String(id));if(!r)return;const item={id:String(r.SeasonID),title:r.SeasonName||r.LeagueName||`Season ${r.SeasonID}`};saveSeason(item);state.seasonId=item.id;savePrefs();fillSeason();closeDrawer();await loadSeason()}
async function addSeasonFromRaw(raw,statusEl){const m=String(raw||'').match(/(?:seasons\/)?(\d{3,})/);if(!m){if(statusEl)statusEl.textContent='Enter a GameSheet season URL or numeric season ID.';return}try{if(statusEl)statusEl.textContent='Checking season…';const info=firstData(await fetchJson(`${API}/season-info/${m[1]}`));if(!info)throw new Error('Season not found');const item={id:String(info.id||m[1]),title:info.title||`Season ${m[1]}`};saveSeason(item);state.seasonId=item.id;savePrefs();fillSeason();closeDrawer();await loadSeason()}catch(e){if(statusEl)statusEl.textContent=`Could not add season: ${e.message}`;else alert(e.message)}}
async function openSeasonFinder(){openDrawer('Find league / season','Search the periodically refreshed public-season catalog',`<div class="season-finder"><div><label class="label">Search league or season</label><div class="season-search-row"><input id="seasonCatalogSearch" type="search" autocomplete="off" placeholder="DVHL, Delaware Valley, 15111…"><select id="seasonSportFilter"><option value="hockey">Hockey</option><option value="all">All sports</option></select></div></div><div id="seasonFinderStatus" class="season-finder-status">Loading season catalog…</div><div id="seasonFinderResults" class="season-results"></div><div class="catalog-note">This is a periodically refreshed snapshot, not GameSheet’s partner-only live directory. If a new season is missing, use its GameSheet URL or season ID below.</div><section class="manual-season"><label class="label">Open by GameSheet URL or season ID</label><div class="manual-season-row"><input id="manualSeasonInput" type="search" inputmode="numeric" placeholder="https://gamesheetstats.com/seasons/15111 or 15111"><button id="manualSeasonAdd" class="soft">Open season</button></div><div id="manualSeasonStatus" class="season-finder-status"></div></section></div>`);const input=$('#seasonCatalogSearch'),sport=$('#seasonSportFilter'),status=$('#seasonFinderStatus'),manual=$('#manualSeasonInput'),manualBtn=$('#manualSeasonAdd'),manualStatus=$('#manualSeasonStatus');try{const rows=await loadSeasonCatalog();const sports=[...new Set(rows.map(x=>String(x.Sport||'')).filter(Boolean))].sort();sport.innerHTML='<option value="hockey">Hockey</option><option value="all">All sports</option>'+sports.filter(x=>x!=='hockey').map(x=>`<option value="${escAttr(x)}">${esc(pretty(x))}</option>`).join('');input.oninput=renderSeasonFinderResults;sport.onchange=renderSeasonFinderResults;renderSeasonFinderResults();input.focus()}catch(e){status.textContent=`Season catalog unavailable: ${e.message}. You can still open a season directly below.`}manualBtn.onclick=()=>addSeasonFromRaw(manual.value,manualStatus);manual.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();manualBtn.click()}}}
async function addSeason(){return openSeasonFinder()}
'''
s = s[:start] + finder_js + '\n' + s[end:]
(ROOT / 'v3.5.html').write_text(s, encoding='utf-8')

stable_path = ROOT / 'gamesheets_plus.html'
stable = stable_path.read_text(encoding='utf-8')
stable = stable.replace('V3.4.2', 'V3.5').replace("'3.4.2'", "'3.5'").replace("'v3.4.2.html'", "'v3.5.html'")
start_items = stable.index('  <div class="items">')
end_items = stable.index('  <div id="originalNote"', start_items)
items = '''  <div class="items">\n    <div class="item"><div class="check">✓</div><div><b>League / season search</b><span>Find known public GameSheet seasons by typing a league name, season name, familiar acronym, or season ID.</span></div></div>\n    <div class="item"><div class="check">✓</div><div><b>Careful acronym fallback</b><span>Explicit abbreviations rank highly; inferred acronyms such as DVHL are deliberately lower-confidence and rank behind normal name matches.</span></div></div>\n    <div class="item"><div class="check">✓</div><div><b>Manual fallback stays available</b><span>The catalog is refreshed periodically, so brand-new seasons can still be opened directly by GameSheet URL or season ID.</span></div></div>\n  </div>\n'''
stable = stable[:start_items] + items + stable[end_items:]
stable_path.write_text(stable, encoding='utf-8')

index_path = ROOT / 'index.html'
index = index_path.read_text(encoding='utf-8')
index = index.replace('<div class="version"><div class="tag current">V3.4.2</div>', '<div class="version"><div class="tag">V3.4.2</div>', 1)
marker = '<section class="versions">\n'
card = '<div class="version"><div class="tag current">V3.5</div><div class="desc"><b>Searchable league and season discovery</b><span>Added a local public-season catalog with type-ahead search, strong name/token matching, cautious acronym inference, current-season ranking, sport filtering, and a direct URL/ID fallback.</span></div><a class="open" href="v3.5.html">Open V3.5</a></div>\n'
assert marker in index
index = index.replace(marker, marker + card, 1)
index_path.write_text(index, encoding='utf-8')

readme_path = ROOT / 'README.md'
readme = readme_path.read_text(encoding='utf-8')
readme = re.sub(r'\*\*Current numbered version:\*\* `v[^`]+`', '**Current numbered version:** `v3.5.html`', readme)
readme = readme.replace('- Full-season schedule browsing and search\n', '- Full-season schedule browsing and search\n- Type-ahead league / season discovery from a periodically refreshed local catalog\n- Conservative acronym fallback for familiar league abbreviations such as DVHL\n')
readme = readme.replace('- **V3.4.1** — natural age/tier ordering for division selectors\n', '- **V3.4.1** — natural age/tier ordering for division selectors\n- **V3.4.2** — explicit Add Players multi-selection flow\n- **V3.5** — searchable league/season catalog with cautious acronym matching\n')
anchor = '## Data quality notes\n'
section = '''## League / season catalog\n\nThe app cannot use GameSheet’s partner-only season-directory search API, so MyHockeyHub ships a periodically refreshed snapshot at [`data/seasons.json`](data/seasons.json). The finder searches that file locally in the browser; normal app use does not scrape season IDs.\n\nSearch ranking favors exact names, starts-with and token matches, explicit acronyms already present in a season name, and current/recent seasons. Generated acronyms are deliberately conservative: for example, **Delaware Valley Hockey League** can be found with **DVHL**, but inferred acronym matches rank below direct textual matches and require an exact acronym match.\n\nThe snapshot can lag newly created seasons, so the finder retains a direct GameSheet season ID / URL fallback.\n\n'''
if anchor in readme and '## League / season catalog' not in readme:
    readme = readme.replace(anchor, section + anchor, 1)
readme_path.write_text(readme, encoding='utf-8')

faq_path = ROOT / 'FAQ.md'
faq = faq_path.read_text(encoding='utf-8')
faq_anchor = '## How do I add a team to My Teams?\n'
season_faq = '''## How do I find or change leagues / seasons?\n\nOpen **Settings → Find league / season**. Start typing a league name, part of a name, a season name, familiar acronym, or season ID. Results update immediately as you type.\n\nDirect text matches rank first. MyHockeyHub can also recognize explicit acronyms in GameSheet names and cautiously infer a familiar acronym when needed—for example, **DVHL** can suggest **Delaware Valley Hockey League**. Inferred acronyms are suggestions rather than authoritative league metadata and intentionally rank below direct name matches.\n\nThe catalog is refreshed periodically rather than live. If a new season is missing, enter its GameSheet season ID or season URL in the manual field at the bottom of the finder.\n\n'''
if faq_anchor in faq and '## How do I find or change leagues / seasons?' not in faq:
    faq = faq.replace(faq_anchor, season_faq + faq_anchor, 1)
old_follow = '''## How do I follow a player?\n\nThere are several ways:\n\n- Open **Players → Add Players** and tap the **☆ star** next to the player.\n- Open **My Teams Roster** and tap the **☆ star** on a player card.\n- Open a game’s **Players** tab and tap the **☆ star** beside a player.\n\nA filled **★** means the player is currently followed.\n\n> **Important:** In the Add Players screen, tapping the player name opens player details. **Tapping the star is what adds the player to My Players.**\n'''
new_follow = '''## How do I follow a player?\n\nThere are several ways:\n\n- Open **Players → Add Players**, check one or more players, then tap **Add Player(s)**. The picker shows a live selection count and includes **Select all** / **Clear** actions.\n- Open **My Teams Roster** and tap the **☆ star** on a player card.\n- Open a game’s **Players** tab and tap the **☆ star** beside a player.\n\nA filled **★** elsewhere means the player is currently followed. In **Add Players**, already-followed players are labeled **Following** and cannot be selected again.\n'''
if old_follow in faq:
    faq = faq.replace(old_follow, new_follow, 1)
faq_path.write_text(faq, encoding='utf-8')

(ROOT / 'data/README.md').write_text('''# Season catalog\n\n`seasons.json` is a manually refreshed snapshot of public GameSheet season metadata used by MyHockeyHub’s client-side league/season finder.\n\nIt is intentionally static because GameSheet’s official season-directory search endpoint is partner-restricted. Normal MyHockeyHub users do **not** scrape GameSheet; they search this local file in the browser.\n\nThe catalog can include source-side test, demo, duplicate, or stale records because it reflects discovered public season metadata. The app ranks likely useful/current hockey seasons higher and keeps a manual season ID/URL fallback for seasons added after the last refresh.\n\nWhen refreshing the snapshot, preserve at least: `SeasonID`, `Sport`, `LeagueName`, `SeasonName`, `StartDate`, `EndDate`, and `StatsUrl`.\n''', encoding='utf-8')
