from pathlib import Path
import re
import runpy

runpy.run_path('tools/build_v3_1.py')
p = Path('v3.1.html')
s = p.read_text()

player_block = r'''function playerTeamOptions(divisionId){const teams=state.teams.filter(t=>!divisionId||t.divisions.has(String(divisionId))),seen=new Map();for(const t of teams){const key=normalize(t.title);if(!seen.has(key))seen.set(key,{ids:[],title:t.title});seen.get(key).ids.push(t.id)}return[...seen.values()].sort((a,b)=>a.title.localeCompare(b.title,undefined,{numeric:true}))}
async function openPlayerPicker(){openDrawer('Add Players','Choose players to follow','<div class="muted">Loading…</div>');const t=myTeam(),myDiv=t?[...t.divisions][0]:'',teams=playerTeamOptions(myDiv),myGroup=teams.find(x=>x.ids.includes(String(t?.id||'')));els.drawerBody.innerHTML=`<div class="pickergrid"><div><label class="label">Division</label><select id="playerDivision">${state.divisions.map(d=>`<option value="${d.id}" ${String(d.id)===String(myDiv)?'selected':''}>${esc(d.title)}</option>`).join('')}</select></div><div><label class="label">Team</label><select id="playerTeam"><option value="">All teams</option>${teams.map(x=>`<option value="${escAttr(x.ids.join(','))}" ${myGroup===x?'selected':''}>${esc(x.title)}</option>`).join('')}</select></div><div style="grid-column:1/-1"><label class="label">Search</label><input id="playerSearch" type="search" placeholder="Player name or jersey"></div></div><div id="playerPickerStatus" class="muted" style="margin:8px 0"></div><div id="playerPickerList" class="pickerlist"></div>`;const rebuildTeams=()=>{const d=$('#playerDivision').value,opts=playerTeamOptions(d);$('#playerTeam').innerHTML='<option value="">All teams</option>'+opts.map(x=>`<option value="${escAttr(x.ids.join(','))}">${esc(x.title)}</option>`).join('');loadPlayerPicker()};$('#playerDivision').onchange=rebuildTeams;$('#playerTeam').onchange=loadPlayerPicker;$('#playerSearch').oninput=renderPlayerPicker;await loadPlayerPicker()}
function extractStandingRows(body){const roots=[],seen=new Set();function walk(v,depth=0){if(v==null||depth>5)return;if(Array.isArray(v)){if(v.length&&v.some(x=>x&&typeof x==='object'&&!Array.isArray(x)))roots.push(v);for(const x of v.slice(0,5))walk(x,depth+1);return}if(typeof v!=='object'||seen.has(v))return;seen.add(v);for(const [k,x] of Object.entries(v)){if(['data','players','standings','rows','results','items','skaters','goalies','entries'].includes(k))walk(x,depth+1)}for(const x of Object.values(v))if(x&&typeof x==='object')walk(x,depth+1)}walk(body);const score=a=>a.reduce((n,r)=>n+(r&&(r.player||r.skater||r.goalie||r.firstName||r.lastName||r.name||r.title||r.stats)?1:0),0);return roots.sort((a,b)=>score(b)-score(a)||b.length-a.length)[0]||[]}
function normalizePlayerResponse(body,kind,divisionId){return extractStandingRows(body).map(r=>normalizePlayer(r,kind,divisionId)).filter(p=>p.id&&p.name)}
function normalizePlayer(r,kind,divisionId){const p=r.player||r.skater||r.goalie||r,team=r.team||p.team||{},stats=r.stats||p.stats||r;const first=p.firstName||r.firstName||'',last=p.lastName||r.lastName||'',name=(p.name||p.title||r.name||r.title||`${first} ${last}`).trim();const id=String(p.id??r.playerId??r.id??'');const teamId=String(team.id??r.teamId??p.teamId??'');const teamObj=state.teams.find(t=>t.id===teamId)||{};return{id,name,kind,number:p.number??p.jersey??r.number??r.jersey??'',position:p.position??r.position??'',teamId,teamTitle:team.title||team.name||r.teamTitle||r.teamName||teamObj.title||'',teamLogo:team.logo||r.teamLogo||teamObj.logo||'',teamAbbr:team.abbr||teamObj.abbr||'',divisionId:String(r.division?.id??p.division?.id??divisionId),divisionTitle:r.division?.title||p.division?.title||state.divisions.find(x=>String(x.id)===String(divisionId))?.title||'',photo:p.photoURL||p.photo||r.photoURL||r.photo||'',g:num(stats.g??stats.goals),a:num(stats.a??stats.assists),pts:num(stats.pts??stats.points),pim:num(stats.pim),sog:num(stats.sog??stats.shots),gaa:stats.gaa??r.gaa??'—',svPct:stats.savePct??stats.svPct??stats.svPercentage??r.savePct??'—',w:stats.w??stats.wins??r.wins??'—',so:stats.so??stats.shutouts??r.shutouts??'—'}}
function num(v){return v==null||v===''?0:Number(v)}
function dedupePlayers(a){const m=new Map();for(const p of a){const old=m.get(p.id);if(!old||Object.keys(p).filter(k=>p[k]!==''&&p[k]!=null).length>Object.keys(old).filter(k=>old[k]!==''&&old[k]!=null).length)m.set(p.id,p)}return[...m.values()].sort((a,b)=>a.name.localeCompare(b.name))}
async function rosterFallback(teamIds,divisionId){for(const teamId of teamIds){const games=state.games.filter(g=>hasTeam(g,teamId)).sort((a,b)=>gameDate(b)-gameDate(a));for(const g of games.slice(0,4)){try{const u=`https://firestore.googleapis.com/v1/projects/gamesheet-production/databases/(default)/documents/seasons/${state.seasonId}/games/${g.gameId}`,d=firestoreData(await fetchJson(u)),side=String(g.home?.id)===String(teamId)?'home':'visitor',team=g[side]||{},players=d?.data?.[side]?.lineup?.players||[];if(players.length)return players.map(p=>normalizePlayer({player:p,team,division:team.division},String(p.position||'').toLowerCase().includes('goalie')?'goalie':'skater',divisionId)).filter(x=>x.id&&x.name)}catch(e){console.warn('Roster fallback failed for game',g.gameId,e)}}}return[]}
async function loadPlayerPicker(){const d=$('#playerDivision')?.value,teamIds=String($('#playerTeam')?.value||'').split(',').filter(Boolean);if(!d)return;$('#playerPickerStatus').textContent='Loading players…';try{const key=`${state.seasonId}:${d}:${teamIds.join(',')||'all'}`;if(!state.playerCache[key]){const base=`?limit=500&offset=0&division=${encodeURIComponent(d)}&gameType=regular_season`,[sk,go]=await Promise.allSettled([fetchJson(`${API}/players/standings/${state.seasonId}${base}&sort=-pts`),fetchJson(`${API}/goalies/standings/${state.seasonId}${base}&sort=gaa`)]),rows=[];if(sk.status==='fulfilled')rows.push(...normalizePlayerResponse(sk.value,'skater',d));if(go.status==='fulfilled')rows.push(...normalizePlayerResponse(go.value,'goalie',d));if(teamIds.length)rows.push(...await rosterFallback(teamIds,d));let merged=dedupePlayers(rows);if(teamIds.length)merged=merged.filter(p=>!p.teamId||teamIds.includes(String(p.teamId)));state.playerCache[key]=merged}renderPlayerPicker();$('#playerPickerStatus').textContent=`${state.playerCache[key].length} players found${teamIds.length?' for selected team':''}`}catch(e){console.error(e);$('#playerPickerStatus').textContent=`Could not load players: ${e.message}`}}
function renderPlayerPicker(){const d=$('#playerDivision')?.value,teamIds=String($('#playerTeam')?.value||'').split(',').filter(Boolean),key=`${state.seasonId}:${d}:${teamIds.join(',')||'all'}`,q=String($('#playerSearch')?.value||'').toLowerCase(),favs=favPlayerMap(),list=(state.playerCache[key]||[]).filter(p=>!q||`${p.name} ${p.teamTitle} ${p.number}`.toLowerCase().includes(q));$('#playerPickerList').innerHTML=list.map(p=>`<div class="pickrow">${logo({title:p.teamTitle,logo:p.teamLogo,abbr:p.teamAbbr},'xs')}<div><div class="pn">${esc(p.name)} ${p.number?`#${esc(p.number)}`:''}</div><div class="pm">${esc(p.teamTitle||'')} · ${esc(p.position||pretty(p.kind))}</div></div><button class="star ${favs[p.id]?'active':''}" data-pick="${escAttr(p.id)}" title="${favs[p.id]?'Unfollow':'Follow'} player">${favs[p.id]?'★':'☆'}</button></div>`).join('')||'<div class="empty">No matching players were returned. Try another team or division.</div>';$('#playerPickerList').querySelectorAll('[data-pick]').forEach(b=>b.onclick=()=>{const p=(state.playerCache[key]||[]).find(x=>x.id===b.dataset.pick);if(!p)return;const m=favPlayerMap();if(m[p.id])delete m[p.id];else m[p.id]=p;saveFavPlayerMap(m);renderPlayerPicker()})}
'''

pattern = re.compile(r'function playerTeamOptions\(divisionId\).*?\nfunction scheduleTeamGroups', re.S)
s2, n = pattern.subn(lambda _: player_block + 'function scheduleTeamGroups', s, count=1)
if n != 1:
    raise RuntimeError(f'clean player block: expected 1 replacement, got {n}')
p.write_text(s2)
